import TextEditor from "@/components/pages/blog/create";
import React from "react";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Zagoo English - Create Blog",
  description: "Generated by create next app",
};

export default function Page() {
  return <TextEditor />;
}
